### ISSUE TITLE
error with cull_mesh script

### ISSUE THREAD

**Issue by UestcJay** [dazinovic/neural-rgbd-surface-reconstruction#38]
hi, many thanks for your great works!  I tried to run the transform_mesh.py and cull_mesh.py scripts on the breakfast_room data. But I get a  error with the cull_mesh script. Do you have any advice how I can resolve this error?

`/home/dl/kaiduo.zhang/LumiNet/cullmesh/neural_rgbd_data/ breakfast_room
Traceback (most recent call last):
  File "/home/dl/kaiduo.zhang/LumiNet/cullmesh/frustum_culling/cull_mesh.py", line 172, in <module>
    cull_mesh(mesh_path, save_path, pose_file, training_poses, intrinsics_path, scene_bounds=scene_bounds)
  File "/home/dl/kaiduo.zhang/LumiNet/cullmesh/frustum_culling/cull_mesh.py", line 81, in cull_mesh
    proc1 = subprocess.Popen(['scontrol', 'show', 'job', os.environ['SLURM_JOBID'], '-d'], stdout=subprocess.PIPE)
  File "/home/dl/kaiduo.zhang/anaconda3/envs/cull/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLURM_JOBID'
`

**Comment by dazinovic** [comment]
The script was written to run on a SLURM-managed GPU cluster. You can remove that part if you are trying to run it locally.
